### ISSUE TITLE
Cannot add new time

### ISSUE THREAD

**Issue by jeroenbe** [tarutin/hovrly#39]
When typing in a new city, Hovrly no longer finds/searches/includes a new time zone. What can I do to help get a better description of this bug?

**Comment by tarutin** [comment]
@jeroenbe Please check now. I think DB is restarting at that time

**Comment by jeroenbe** [comment]
Still happening. Ill try at a different time and report back.

**Comment by tarutin** [comment]
@jeroenbe OK. One moment: maybe are U using some VPN or something?

**Comment by oreopot** [comment]
I am having the same issue as well.
I have tried:
- Clearing the cache 
- re-installing the app  
- I do not have a VPN running

**Comment by robcalcroft** [comment]
same issue, i search, nothing pops up and when i hit enter the search term disappears

**Comment by fsorodrigues** [comment]
was having the same issue as described: would try to add a new tz, but hitting enter the search would just disappear.
when I switched networks, the search started working again.

has to be something to do with the network as the error was only happening on my work's corporate network (which I know has some aggressive controls)

**Comment by tarutin** [comment]
I fixed few things. Try again.

**Comment by kentbetita** [comment]
> When typing in a new city, Hovrly no longer finds/searches/includes a new time zone.

hey @tarutin, i'm currently experiencing the same issue. can you please share any information as to why this is happening? that would be really helpful. thank you.

**Comment by mvmn** [comment]
Same for me - is broken for about a month now, and still broken

P.S. Switching to a reserve internet provider helped - search started to work again. Definitely somehow related to an ISP I use - but not clear how and why

**Comment by tarutin** [comment]
@kentbetita @mvmn We checked this issue and did not find the cause of the failure. Everything works. I think the problem is in the VPN or ISPs of some countries. Now the DB is located on the territory of the EU.
